AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: ''

Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 120
    MemorySize: 512
    Environment:
      Variables:
        STAGE: !Ref Stage
        NODE_ENV: production

Resources:
  FaceSearchApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: api/lambda.handler
      CodeUri: .
      Environment:
        Variables:
          S3_BUCKET: !Ref FaceImageBucket
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3ReadPolicy:
            BucketName: !Ref FaceImageBucket
        - RekognitionReadPolicy:
            CollectionId: skooldio
      Events:
        FaceGetEvent:
          Type: Api
          Properties:
            Path: /face
            Method: get
        FacePostEvent:
          Type: Api
          Properties:
            Path: /face
            Method: post

  FaceImageBucket:
    Type: AWS::S3::Bucket

Outputs:
  S3Bucket:
    Description: "S3 Bucket name that will trigger a Lambda function upon new objects insertion"
    Value: !Ref FaceImageBucket